/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                           (c) Copyright 1992-1999, Jean J. Labrosse, Weston, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
									changed by luyl
*********************************************************************************************************
*/

#include    <stdio.h>
#include    <string.h>
#include    <ctype.h>
#include    <stdlib.h>
#include	<conio.h>

#include	<windows.h>
#include	<mmsystem.h>	//包含时钟函数的头文件，需要windows.h的支持

#include    "os_cpu.h"
#include    "os_cfg.h"
#include    "ucos_ii.h"


#include    "user.h"




//#include	"commands.h"
//#include	"shelltask.h"

//#include	"fs_api.h"
//#include	"fs_clib.h"
//#include    "pc.h"